<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>g</string>
		<string>gi</string>
		<string>gd</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(if)\b|(\{|\b(then)\b)$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|(od|fi|esac)\b)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>gap</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pipeline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compound-command</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heredoc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#herestring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#redirection</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pathname</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gap</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.gap</string>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:=</string>
					<key>name</key>
					<string>variable.parameter.gap</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(function)\s*(\([^\)]*\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.gap</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.gap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>end;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.gap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.gap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:if|then|else|elif|fi|for|in|do|od|end|continue|while|until|return|Error|-&gt;)\b</string>
					<key>name</key>
					<string>keyword.control.gap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![-/])\b(?:local)\b</string>
					<key>name</key>
					<string>storage.modifier.gap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:Assert|Info|IsBound|QUIT|TryNextMethod|Unbind|mod|quit|rec)\b</string>
					<key>name</key>
					<string>keyword.control.gap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;=?|&gt;=?|=</string>
					<key>name</key>
					<string>keyword.control.gap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:and|or|not)\b</string>
					<key>name</key>
					<string>keyword.control.gap</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;|&amp;&amp;|&amp;|\|\|</string>
					<key>name</key>
					<string>keyword.operator.list.gap</string>
				</dict>
			</array>
		</dict>
		<key>loop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(while|until)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(od)\b</string>
					<key>name</key>
					<string>meta.scope.while-loop.gap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(if)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(fi)\b</string>
					<key>name</key>
					<string>meta.scope.if-block.gap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.gap</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.gap</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$?"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gap</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gap</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.gap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\$`"\\\n]</string>
							<key>name</key>
							<string>constant.character.escape.gap</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>support</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![-/])\b(?:DeclareOperation|DeclareGlobalFunction|DeclareGlobalVariable|DeclareAttribute|DeclareProperty|DeclareCategory|DeclareFilter|DeclareRepresentation|DeclareInfoClass|DeclareCategoryCollections|DeclareSynonym)</string>
					<key>name</key>
					<string>support.function.declare.gap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![-/])\b(?:InstallMethod|InstallOtherMethod|NewType|Objectify|NewFamily|InstallTrueMethod|InstallGlobalFunction|ObjectifyWithAttributes|BindGlobal|BIND_GLOBAL|InstallValue)</string>
					<key>name</key>
					<string>support.function.install.gap</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gap</string>
	<key>uuid</key>
	<string>DDEEA3ED-6B1C-11D9-8B10-000D93589AF6</string>
</dict>
</plist>
